pub(crate) struct Dict {
    words: Vec<(String, String)>,
    chars: Vec<(String, String)>,
    overwrites: Vec<(String, String)>,
}

impl Dict {
    pub(crate) fn convert(&self, s: String) -> String {
        let mut s = s;
        for (from, to) in &self.words {
            s = s.replace(from, to);
        }
        for (from, to) in &self.chars {
            s = s.replace(from, to);
        }
        for (from, to) in &self.overwrites {
            s = s.replace(from, to);
        }
        s
    }

    #[rustfmt::skip]
    pub(crate) fn build() -> Self {
        Self {

            words:vec![
        ("あなたさま".to_string(), "贵様".to_string()),
        ("貴方様".to_string(), "贵様".to_string()),
        ("あなた".to_string(), "贵様".to_string()),
        ("貴方".to_string(), "贵樣".to_string()),
        ("きみ".to_string(), "贵樣".to_string()),
        ("君".to_string(), "贵樣".to_string()),
        ("おまえ".to_string(), "贵様".to_string()),
        ("お前".to_string(), "贵樣".to_string()),
        ("あんた".to_string(), "贵樣".to_string()),
        ("てめぇ".to_string(), "贵樣".to_string()),
        ("てめえ".to_string(), "贵樣".to_string()),
        ("てめー".to_string(), "贵樣".to_string()),
        ("汝".to_string(), "贵樣".to_string()),
        ("大変だ".to_string(), "大變た".to_string()),
        ("たいへん".to_string(), "大變".to_string()),
        ("大変".to_string(), "大變".to_string()),
        ("それ".to_string(), "そね".to_string()),
        ("とても".to_string(), "極度".to_string()),
        ("めっちゃ".to_string(), "極度".to_string()),
        ("おおいに".to_string(), "極度".to_string()),
        ("大いに".to_string(), "極度".to_string()),
        ("きわめて".to_string(), "極度".to_string()),
        ("極めて".to_string(), "極度".to_string()),
        ("たいわん".to_string(), "中华民国".to_string()),
        ("台湾".to_string(), "中华民国".to_string()),
        ("中国共産党員".to_string(), "中國共产党员".to_string()),
        ("中国共産党".to_string(), "中國共产党".to_string()),
        ("中共".to_string(), "中國共产党".to_string()),
        ("中国人".to_string(), "中华民族".to_string()),
        ("中国語".to_string(), "中文".to_string()),
        ("優秀".to_string(), "优秀".to_string()),
        ("偉人".to_string(), "优秀の人材".to_string()),
        ("エリート".to_string(), "优秀の人材".to_string()),
        ("逸材".to_string(), "优秀の人材".to_string()),
        ("秀才".to_string(), "优秀の人材".to_string()),
        ("才人".to_string(), "优秀の人材".to_string()),
        ("鬼才".to_string(), "优秀の人材".to_string()),
        ("奇才".to_string(), "优秀の人材".to_string()),
        ("天才".to_string(), "优秀の人材".to_string()),
        ("忙しい".to_string(), "多忙".to_string()),
        ("マインクラフト".to_string(), "我的世界".to_string()),
        ("マイクラ".to_string(), "我的世界".to_string()),
        ("ごはん".to_string(), "食事".to_string()),
        ("ご飯".to_string(), "食事".to_string()),
        ("御飯".to_string(), "食事".to_string()),
        ("よめない".to_string(), "解读不可".to_string()),
        ("読めない".to_string(), "解读不可".to_string()),
        ("よめません".to_string(), "解读不可".to_string()),
        ("読めません".to_string(), "解读不可".to_string()),
        ("勉強".to_string(), "勉强".to_string()),
        ("値段".to_string(), "金额".to_string()),
        ("金額".to_string(), "金额".to_string()),
        ("買う".to_string(), "购入".to_string()),
        ("購入".to_string(), "购入".to_string()),
        ("広大".to_string(), "雄大".to_string()),
        ("広い".to_string(), "雄大な".to_string()),
        ("おすすめ".to_string(), "推奨".to_string()),
        ("オススメ".to_string(), "才ㄡㄡㄨ".to_string()),
        ("難しい".to_string(), "困难".to_string()),
        ("危険".to_string(), "危險".to_string()),
        ("スポーツ".to_string(), "ヌポ一ッ".to_string()),
        ("わたし".to_string(), "仆".to_string()),
        ("ぼく".to_string(), "仆".to_string()),
        ("クジラ".to_string(), "鲸".to_string()),
        ("くじら".to_string(), "鲸".to_string()),
        ("海老".to_string(), "虾".to_string()),
        ("エビ".to_string(), "虾".to_string()),
        ("えび".to_string(), "虾".to_string()),
        ("アワビ".to_string(), "".to_string()),
        ("あわび".to_string(), "鲍".to_string()),
        ("タラ".to_string(), "鳕".to_string()),
        ("ウナギ".to_string(), "鳗".to_string()),
        ("うなぎ".to_string(), "鳗".to_string()),
        ("カツオ".to_string(), "鲣".to_string()),
        ("かつお".to_string(), "鲣".to_string()),
        ("ナマズ".to_string(), "鲶".to_string()),
        ("なまず".to_string(), "鲶".to_string()),
        ("サバ".to_string(), "鲭".to_string()),
        ("スズキ".to_string(), "鲈".to_string()),
        ("蝶鮫".to_string(), "鲟".to_string()),
        ("チョウザメ".to_string(), "鲟".to_string()),
        ("ちょうざめ".to_string(), "鲟".to_string()),
        ("ボラ".to_string(), "鲻".to_string()),
        ("ワニ".to_string(), "鳄".to_string()),
        ("はい".to_string(), "ばい".to_string()),
        ("おｋ".to_string(), "ばい(了承)".to_string()),
        ("おＫ".to_string(), "ばい(了承)".to_string()),
        ("うまい".to_string(), "ラまい".to_string()),
        ("美味い".to_string(), "ラまい".to_string()),
        ("美味しい".to_string(), "美味レい".to_string()),
        ("おいしい".to_string(), "美味レい".to_string()),
        ("困った".to_string(), "難㩘た".to_string()),
        ("するのだが".to_string(), "ずゑゐだ力゛?".to_string()),
        ("そうか".to_string(), "そラ力".to_string()),
        ("まじかよ".to_string(), "まレ゛かょ".to_string()),
        ("まじか".to_string(), "まレ゛かょ".to_string()),
        ("協力".to_string(), "团结".to_string()),
        ("団結".to_string(), "团结".to_string()),
        ("警察".to_string(), "武装警察".to_string()),
        ("県警".to_string(), "民警".to_string()),
        ("描く".to_string(), "描画ずゑ".to_string()),
        ("タピオカ".to_string(), "夕匕オ力".to_string()),
        ("辞書".to_string(), "辞畫".to_string()),
        ("信頼".to_string(), "信赖".to_string()),
        ("盾".to_string(), "防暴盾".to_string()),
        ("みんな".to_string(), "人民".to_string()),
        ("皆".to_string(), "人民".to_string()),
        ("スマホ".to_string(), "HUAWEI".to_string()),
        ("覚醒剤".to_string(), "觉せソ剂".to_string()),
        ("お願いします".to_string(), "御願いレまず(敵意)".to_string()),
        ("おねがいします".to_string(), "御願いレまず(敵意)".to_string()),
        ("豆腐".to_string(), "ピータソ豆腐".to_string()),
        ("フォロー".to_string(), "㇇ォー".to_string()),
        ("必要".to_string(), "必买".to_string()),
        ("労働".to_string(), "極度勞動".to_string()),
        ("仕事".to_string(), "極度勞動".to_string()),
        ("ソ連".to_string(), "ン匕工ㇳ社会主儀共和國連邞".to_string()),
        ("ソビエト連邦".to_string(), "ン匕工ㇳ社会主儀共和國連邞".to_string()),
        ("ソビエト社会主義共和国連邦".to_string(), "ン匕工ㇳ社会主儀共和國連邞".to_string()),
        ("通り道".to_string(), "轨道上".to_string()),
        ("特殊".to_string(), "異端".to_string()),
        ("ガチャガチャ".to_string(), "ガタガタ".to_string()),
        ("ピーラー".to_string(), "匕゜ラー".to_string()),
        ("男性".to_string(), "绅士".to_string()),
        ("たばこ".to_string(), "烟草".to_string()),
        ("タバコ".to_string(), "烟草".to_string()),
        ("取り扱い".to_string(), "取及".to_string()),
        ("コンビニ".to_string(), "⊐ソ匕゛㆓".to_string()),
        ("ゾンビ".to_string(), "廃人(ン゛ソヒ)".to_string()),
        ("サンドイッチ".to_string(), "サソㇳ゛亻千".to_string()),
        ("ウーパールーパー".to_string(), "墨西哥山椒魚".to_string()),
        ("出勤".to_string(), "每日任务".to_string()),
        ("絶対".to_string(), "怭㒄".to_string()),
        ("練習".to_string(), "綀漝".to_string()),
        ("豪邸".to_string(), "ごラてい".to_string()),
        ("自宅".to_string(), "ごラてい".to_string()),
        ("ホルモン".to_string(), "朩儿乇ソ".to_string()),
        ("かにかま".to_string(), "蟹肉棒".to_string()),
        ("カニカマ".to_string(), "蟹肉棒".to_string()),
        ("とうもろこし".to_string(), "トウモ口コミ".to_string()),
        ("トウモロコシ".to_string(), "トウモ口コミ".to_string()),
        ("コーン".to_string(), "トウモ口コミ".to_string()),
        ("マイクロソフト".to_string(), "龴亻クソソ㇇ㇳ".to_string()),
        ("マイクソソフト".to_string(), "龴亻クソソ㇇ㇳ".to_string()),
        ("万が一".to_string(), "ㄪヶ壱".to_string()),
        ("もうある".to_string(), "既有".to_string()),
        ("アプリケーション".to_string(), "アプ刂ケーツ゚彐ソ".to_string()),
        ("アプリ".to_string(), "アプ刂ケーツ゚彐ソ".to_string()),
        ("評価".to_string(), "评价".to_string()),
        ("食物連鎖".to_string(), "食牣繊维".to_string()),
        ("流行り".to_string(), "ビッグウーヱブ".to_string()),
        ("流行".to_string(), "ビッグウーヱブ".to_string()),
        ("Sky:CotL".to_string(), "Sky光·遇".to_string()),
        ("シェーダー".to_string(), "光影".to_string()),
        ("ソーラーパネル".to_string(), "ンーラー⼋礻ゑ".to_string()),
        ("ソーラー".to_string(), "ンーラー⼋礻ゑ".to_string()),
        ("チンジャオロース".to_string(), "青椒肉丝".to_string()),
        ("ラーメン".to_string(), "うーメソ".to_string()),
        ("エビチリ".to_string(), "工匕チり".to_string()),
        ("からあげ".to_string(), "唐まげ".to_string()),
        ("唐揚げ".to_string(), "唐まげ".to_string()),
        ("餃子".to_string(), "ギヨーザー".to_string()),
        ("ギョウザ".to_string(), "ギヨーザー".to_string()),
        ("アサヒビール".to_string(), "アサ匕ビㄦ(極度乾燥)".to_string()),
        ("ビール".to_string(), "アサ匕ビㄦ(極度乾燥)".to_string()),
        ("ハイボール".to_string(), "⼋亻ボㄦ".to_string()),
        ("角瓶".to_string(), "⼋亻ボㄦ瓶子".to_string()),
        ("英才教育".to_string(), "芵オ教育".to_string()),
        ("来世利益".to_string(), "來抴利益".to_string()),
        ("リア充".to_string(), "现抴充実民".to_string()),
        ("紹介".to_string(), "介绍".to_string()),
        ("安全".to_string(), "安全的".to_string()),
        ("安い".to_string(), "洝価的".to_string()),
        ("あけおめ".to_string(), "新年快乐".to_string()),
        ("牛丼".to_string(), "牛肉丼".to_string()),
        ("かわいい".to_string(), "可爱ぃ".to_string()),
        ("カワイイ".to_string(), "可爱ぃ".to_string()),
        ("可愛い".to_string(), "可爱ぃ".to_string()),
        ("挨拶".to_string(), "诶拶".to_string()),
        ("しめ鯖".to_string(), "締ぬサ⼋゜".to_string()),
        ("しめさば".to_string(), "締ぬサ⼋゜".to_string()),
        ("シメサバ".to_string(), "締ぬサ⼋゜".to_string()),
        ("サラダ".to_string(), "サラ⼋゛".to_string()),
        ("バレンタイン".to_string(), "⼋゜レソ夕亻ソ・テー".to_string()),
        ("熱々".to_string(), "あっあっ".to_string()),
        ("アツアツ".to_string(), "あっあっ".to_string()),
        ("あつあつ".to_string(), "あっあっ".to_string()),
        ("オリーブオイル".to_string(), "橄榄油".to_string()),
        ("風味".to_string(), "味道".to_string()),
        ("香り".to_string(), "味道".to_string()),
        ("匂い".to_string(), "味道".to_string()),
        ("ニコニコ".to_string(), "二ゴ二ゴ".to_string()),
        ("両手".to_string(), "双手".to_string()),
        ("マツコ".to_string(), "龴ツ⊐".to_string()),
        ("の知らない世界".to_string(), "的未知的世界".to_string()),
        ("コムドット".to_string(), "⊐゛ㄙㇳッㇳ".to_string()),
        ("東欧".to_string(), "东欧洲".to_string()),
        ("ウクライナ".to_string(), "ワクう亻ナ".to_string()),
        ("エンターテインメント".to_string(), "娱乐".to_string()),
        ("エンタメ".to_string(), "娱乐".to_string()),
        ("トレンド".to_string(), "㳘㣔".to_string()),
        ("トピック".to_string(), "话题".to_string()),
        ("バター".to_string(), "黄油".to_string()),
        ("百聞は一見に如かず".to_string(), "眼见为实".to_string()),
        ("誕生".to_string(), "生誔".to_string()),
        ("フィギュアスケート".to_string(), "花样滑冰".to_string()),
        ("スケート".to_string(), "花样滑冰".to_string()),
        ("オリンピック".to_string(), "奥林匹克".to_string()),
        ("犠牲".to_string(), "牺牲".to_string()),
        ("うんこ".to_string(), "ラんこ".to_string()),
        ("うんち".to_string(), "ラんㄘ".to_string()),
        ("常識".to_string(), "常识".to_string()),
        ("アへ".to_string(), "アベ".to_string()),
        ("トイレ".to_string(), "洗手间".to_string()),
        ("といれ".to_string(), "洗手间".to_string()),
        ("やばい".to_string(), "紧急情况".to_string()),
        ("花粉症".to_string(), "花粉过敏".to_string()),
        ("シロノワール".to_string(), "シ口ノワㄦ".to_string()),
        ("うどん".to_string(), "ラどん".to_string()),
        ("リンガーハット".to_string(), "刂ン力一八ッㇳ".to_string()),
        ("ステーキ".to_string(), "いぎなリ🚀ㄡ亍一キ".to_string()),
        ("お子様ランチ".to_string(), "御子樣ラƕㄘ".to_string()),
        ("ランチ".to_string(), "ラƕㄘ".to_string()),
        ("スポンジ".to_string(), "スポンツ".to_string()),
        ("日本製".to_string(), "日式".to_string()),
        ("スリッパ".to_string(), "ス刂シパ".to_string()),
        ("新鮮".to_string(), "シソㆤソ".to_string()),
        ("爪楊枝".to_string(), "つまようど".to_string()),
        ("つまようじ".to_string(), "つまじうよ".to_string()),
        ("秀逸".to_string(), "秀悦".to_string()),
        ("魔法".to_string(), "まほう".to_string()),
        ("マクドナルド".to_string(), "麦当劳".to_string()),
        ("マクド".to_string(), "麦当劳".to_string()),
        ("マック".to_string(), "麦当劳".to_string()),
        ("妊娠".to_string(), "怀孕".to_string()),
        ("優等生".to_string(), "优秀學生".to_string()),
        ("トロイの木馬".to_string(), "ㇳ口亻的木马".to_string()),
        ("途中".to_string(), "中途".to_string()),
        ("フリー".to_string(), "自由".to_string()),
        ("勤労".to_string(), "努力工作".to_string()),
        ("タワー".to_string(), "塔".to_string()),
        ("ぴったり".to_string(), "ひっだり".to_string()),
        ("レストラン".to_string(), "レヌㇳうン".to_string()),
        ("君が代".to_string(), "义勇军进行曲".to_string()),
        ("毛沢東".to_string(), "毛泽东".to_string()),
        ("伝説".to_string(), "传说".to_string()),
        ("夕飯".to_string(), "晚餐".to_string()),
        ("夕食".to_string(), "晚餐".to_string()),
        ("昼食".to_string(), "午餐".to_string()),
        ("朝食".to_string(), "早餐".to_string()),
        ("バーガー".to_string(), "⼋゛ー力".to_string()),
        ("TikTok".to_string(), "抖音".to_string()),
        ("Tiktok".to_string(), "抖音".to_string()),
        ("tikTok".to_string(), "抖音".to_string()),
        ("ティックトック".to_string(), "抖音".to_string()),
        ("シリーズ".to_string(), "系列".to_string()),
        ("リアルタイム".to_string(), "即时的".to_string()),
        ("繁栄".to_string(), "繁荣".to_string()),
        ("よくばり".to_string(), "贪婪的".to_string()),
        ("牛乳".to_string(), "牛奶".to_string()),
        ("テロ".to_string(), "恐怖主义".to_string()),
        ("ゴーヤ".to_string(), "苦瓜".to_string()),
        ("ゴーヤー".to_string(), "苦瓜".to_string()),
        ("菌糸".to_string(), "菌氏".to_string()),
        ("をしましょう".to_string(), "(しなさい)".to_string()),
        ("しましょう".to_string(), "(しなさい)".to_string()),
        ("をしなさい".to_string(), "(しなさい)".to_string()),
        ("ライブラリ".to_string(), "図書馆".to_string()),
            ],

            chars:vec![
        ("一".to_string(), "壱".to_string()),
        ("二".to_string(), "贰".to_string()),
        ("三".to_string(), "叁".to_string()),
        ("四".to_string(), "䦉".to_string()),
        ("五".to_string(), "伍".to_string()),
        ("六".to_string(), "陸".to_string()),
        ("七".to_string(), "柒".to_string()),
        ("八".to_string(), "捌".to_string()),
        ("九".to_string(), "玖".to_string()),
        ("十".to_string(), "什".to_string()),
        ("百".to_string(), "佰".to_string()),
        ("千".to_string(), "仟".to_string()),
        ("う".to_string(), "ラ".to_string()),
        ("か".to_string(), "力".to_string()),
        ("が".to_string(), "力゛".to_string()),
        ("くく".to_string(), "ㄍ".to_string()),
        ("く".to_string(), "ㄑ".to_string()),
        ("ぐ".to_string(), "ㄑ゛".to_string()),
        ("さ".to_string(), "ㄜ".to_string()),
        ("ざ".to_string(), "ㄜ゛".to_string()),
        ("し".to_string(), "レ".to_string()),
        ("じ".to_string(), "レ゛".to_string()),
        ("す".to_string(), "ず".to_string()),
        ("せ".to_string(), "ㄝ".to_string()),
        ("ぜ".to_string(), "ㄝ゛".to_string()),
        ("ち".to_string(), "ㄘ".to_string()),
        ("ぢ".to_string(), "ㄘ゛".to_string()),
        ("ね".to_string(), "れ".to_string()),
        ("の".to_string(), "ゐ".to_string()),
        ("ら".to_string(), "꘥".to_string()),
        ("り".to_string(), "".to_string()), // hub-F6AD
        ("る".to_string(), "ゑ".to_string()),
        ("ん".to_string(), "ƕ".to_string()),
        ("イ".to_string(), "亻".to_string()),
        ("エ".to_string(), "卫".to_string()),
        ("オ".to_string(), "才".to_string()),
        ("コ".to_string(), "⊐".to_string()),
        ("ゴ".to_string(), "⊐゛".to_string()),
        ("シ".to_string(), "ツ゚".to_string()),
        ("ジ".to_string(), "ツ゚゛".to_string()),
        ("セ".to_string(), "乜".to_string()),
        ("ゼ".to_string(), "乜゛".to_string()),
        ("ス".to_string(), "ㄡ".to_string()),
        ("ズ".to_string(), "ㄡ゛".to_string()),
        ("ソ".to_string(), "".to_string()), // hub-F6F3
        ("ゾ".to_string(), "".to_string()), // hub-F512
        ("タ".to_string(), "夕".to_string()),
        ("ダ".to_string(), "夕゛".to_string()),
        ("チ".to_string(), "千".to_string()),
        ("ヂ".to_string(), "千゛".to_string()),
        ("テ".to_string(), "亍".to_string()),
        ("デ".to_string(), "亍゛".to_string()),
        ("ト".to_string(), "ㇳ".to_string()),
        ("ト".to_string(), "ㇳ゛".to_string()),
        ("ネ".to_string(), "礻".to_string()),
        ("ハ".to_string(), "八".to_string()),
        ("バ".to_string(), "⼋゛".to_string()),
        ("パ".to_string(), "⼋゜".to_string()),
        ("ヒ".to_string(), "匕".to_string()),
        ("ビ".to_string(), "匕゛".to_string()),
        ("ピ".to_string(), "匕゜".to_string()),
        ("フ".to_string(), "㇇".to_string()),
        ("ブ".to_string(), "㇇゛".to_string()),
        ("プ".to_string(), "㇇゜".to_string()),
        ("ホ".to_string(), "朩".to_string()),
        ("ボ".to_string(), "㝳".to_string()),
        ("ポ".to_string(), "朮".to_string()),
        ("マ".to_string(), "龴".to_string()),
        ("ム".to_string(), "ㄙ".to_string()),
        ("メ".to_string(), "ㄨ".to_string()),
        ("ヨ".to_string(), "彐".to_string()),
        ("リ".to_string(), "刂".to_string()),
        ("ル".to_string(), "ㄦ".to_string()),
        ("ロ".to_string(), "口".to_string()),
        ("ン".to_string(), "".to_string()), // hub-F001
        ("".to_string(), "ン".to_string()), // F6F3
        ("".to_string(), "ソ".to_string()), // F001
        ("".to_string(), "リ".to_string()), // F6AD
        ("".to_string(), "ン゛".to_string()), // F512
        ("貴".to_string(), "贵".to_string()),
        ("様".to_string(), "樣".to_string()),
        ("国".to_string(), "國".to_string()),
        ("産".to_string(), "产".to_string()),
        ("増".to_string(), "增".to_string()),
        ("読".to_string(), "读".to_string()),
        ("会".to_string(), "會".to_string()),
        ("黒".to_string(), "黑".to_string()),
        ("私".to_string(), "仆".to_string()),
        ("僕".to_string(), "仆".to_string()),
        ("俺".to_string(), "仆".to_string()),
        ("神".to_string(), "神".to_string()),
        ("顔".to_string(), "颜".to_string()),
        ("友".to_string(), "发".to_string()),
        ("説".to_string(), "说".to_string()),
        ("参".to_string(), "说".to_string()),
        ("帯".to_string(), "带".to_string()),
        ("毎".to_string(), "每".to_string()),
        ("雑".to_string(), "杂".to_string()),
        ("悪".to_string(), "恶".to_string()),
        ("病".to_string(), "㾍".to_string()),
        ("売".to_string(), "壳".to_string()),
        ("乗".to_string(), "乘".to_string()),
        ("社".to_string(), "社".to_string()),
        ("商".to_string(), "啇".to_string()),
        ("西".to_string(), "酉".to_string()),
        ("歌".to_string(), "哥".to_string()),
        ("楽".to_string(), "乐".to_string()),
        ("舞".to_string(), "橆".to_string()),
        ("踏".to_string(), "䠌".to_string()),
        ("絶".to_string(), "絕".to_string()),
        ("学".to_string(), "學".to_string()),
        ("行".to_string(), "㣔".to_string()),
        ("払".to_string(), "㺨".to_string()),
        ("毒".to_string(), "毐".to_string()),
        ("苺".to_string(), "䓯".to_string()),
        ("裁".to_string(), "臷".to_string()),
        ("輩".to_string(), "辈".to_string()),
        ("覚".to_string(), "觉".to_string()),
        ("糸".to_string(), "ㄠ".to_string()),
        ("市".to_string(), "ㄭ".to_string()),
        ("帰".to_string(), "归".to_string()),
        ("亀".to_string(), "龟".to_string()),
        ("海".to_string(), "诲".to_string()),
        ("焼".to_string(), "燒".to_string()),
        ("母".to_string(), "毋".to_string()),
        ("変".to_string(), "娈".to_string()),
        ("済".to_string(), "济".to_string()),
        ("次".to_string(), "㳄".to_string()),
        ("喉".to_string(), "㬋".to_string()),
        ("嬉".to_string(), "嬯".to_string()),
        ("巻".to_string(), "卷".to_string()),
        ("税".to_string(), "稅".to_string()),
        ("緑".to_string(), "绿".to_string()),
        ("赤".to_string(), "亦".to_string()),
        ("青".to_string(), "⾭".to_string()),
        ("白".to_string(), "⾅".to_string()),
        ("黄".to_string(), "黃".to_string()),
        ("宮".to_string(), "宫".to_string()),
        ("蚊".to_string(), "蚁".to_string()),
        ("暇".to_string(), "睱".to_string()),
        ("清".to_string(), "请".to_string()),
        ("経".to_string(), "继".to_string()),
        ("宫".to_string(), "宫".to_string()),
        ("歴".to_string(), "历".to_string()),
        ("草".to_string(), "䓍".to_string()),
        ("噛".to_string(), "嚙".to_string()),
        ("氷".to_string(), "冰".to_string()),
        ("呪".to_string(), "口兄".to_string()),
        ("温".to_string(), "溫".to_string()),
        ("靴".to_string(), "鞋".to_string()),
        ("溶".to_string(), "熔".to_string()),
        ("蛯".to_string(), "虾".to_string()),
        ("足".to_string(), "腳".to_string()),
        ("剣".to_string(), "锈".to_string()),
        ("脳".to_string(), "脑".to_string()),
        ("縦".to_string(), "纵".to_string()),
        ("賛".to_string(), "赞".to_string()),
        ("険".to_string(), "险".to_string()),
        ("齢".to_string(), "龄".to_string()),
        ("院".to_string(), "唍".to_string()),
        ("邦".to_string(), "邞".to_string()),
        ("修".to_string(), "俢".to_string()),
        ("料".to_string(), "㪵".to_string()),
        ("摂".to_string(), "摄".to_string()),
        ("録".to_string(), "录".to_string()),
        ("鶏".to_string(), "鸡".to_string()),
        ("洗".to_string(), "诜".to_string()),
        ("礼".to_string(), "礼".to_string()),
        ("慰".to_string(), "㷉".to_string()),
        ("虫".to_string(), "蟲".to_string()),
        ("銭".to_string(), "钱".to_string()),

        // Japanese Kanji to Simplified Chinese
        ("礙".to_string(),"碍".to_string()),("愛".to_string(),"爱".to_string()),("藹".to_string(),"蔼".to_string()),("襖".to_string(),"袄".to_string()),("壩".to_string(),"坝".to_string()),("罷".to_string(),"罢".to_string()),("敗".to_string(),"败".to_string()),("擺".to_string(),"摆".to_string()),("弁4".to_string(),"办".to_string()),("絆".to_string(),"绊".to_string()),("頒".to_string(),"颁".to_string()),("謗".to_string(),"谤".to_string()),("綁".to_string(),"绑".to_string()),("幫".to_string(),"帮".to_string()),("報".to_string(),"报".to_string()),("飽".to_string(),"饱".to_string()),("剝".to_string(),"剥".to_string()),("備".to_string(),"备".to_string()),("憊".to_string(),"惫".to_string()),("狽".to_string(),"狈".to_string()),("貝".to_string(),"贝".to_string()),("輩".to_string(),"辈".to_string()),("繃".to_string(),"绷".to_string()),("幣".to_string(),"币".to_string()),("畢".to_string(),"毕".to_string()),("斃".to_string(),"毙".to_string()),("閉".to_string(),"闭".to_string()),("筆".to_string(),"笔".to_string()),("変".to_string(),"变".to_string()),("弁1".to_string(),"辩".to_string()),("弁2".to_string(),"辫".to_string()),("貶".to_string(),"贬".to_string()),("編".to_string(),"编".to_string()),("辺".to_string(),"边".to_string()),("標".to_string(),"标".to_string()),("別".to_string(),"别".to_string()),("癟".to_string(),"瘪".to_string()),("鼈".to_string(),"鳖".to_string()),("賓".to_string(),"宾".to_string()),("濱".to_string(),"滨".to_string()),("瀕".to_string(),"濒".to_string()),("併".to_string(),"并".to_string()),("餅".to_string(),"饼".to_string()),("蔔".to_string(),"卜".to_string()),("駁".to_string(),"驳".to_string()),("撥".to_string(),"拨".to_string()),("補".to_string(),"补".to_string()),("財".to_string(),"财".to_string()),("慚".to_string(),"惭".to_string()),("燦".to_string(),"灿".to_string()),("倉".to_string(),"仓".to_string()),("滄".to_string(),"沧".to_string()),("艙".to_string(),"舱".to_string()),("蒼".to_string(),"苍".to_string()),("冊".to_string(),"册".to_string()),("側".to_string(),"侧".to_string()),("廁".to_string(),"厕".to_string()),("測".to_string(),"测".to_string()),("層".to_string(),"层".to_string()),("蟬".to_string(),"蝉".to_string()),("纏".to_string(),"缠".to_string()),("饞".to_string(),"馋".to_string()),("顫".to_string(),"颤".to_string()),("産".to_string(),"产".to_string()),("鏟".to_string(),"铲".to_string()),("闡".to_string(),"阐".to_string()),("摻".to_string(),"掺".to_string()),("攙".to_string(),"搀".to_string()),("償".to_string(),"偿".to_string()),("嘗".to_string(),"尝".to_string()),("腸".to_string(),"肠".to_string()),("長".to_string(),"长".to_string()),("暢".to_string(),"畅".to_string()),("廠".to_string(),"厂".to_string()),("場".to_string(),"场".to_string()),("鈔".to_string(),"钞".to_string()),("徹".to_string(),"彻".to_string()),("車".to_string(),"车".to_string()),("塵".to_string(),"尘".to_string()),("沈".to_string(),"沉".to_string()),("陳".to_string(),"陈".to_string()),("襯".to_string(),"衬".to_string()),("懲".to_string(),"惩".to_string()),("誠".to_string(),"诚".to_string()),("撐".to_string(),"撑".to_string()),("遅".to_string(),"迟".to_string()),("馳".to_string(),"驰".to_string()),("恥".to_string(),"耻".to_string()),("歯".to_string(),"齿".to_string()),("寵".to_string(),"宠".to_string()),("沖".to_string(),"冲".to_string()),("疇".to_string(),"畴".to_string()),("籌".to_string(),"筹".to_string()),("綢".to_string(),"绸".to_string()),("醜".to_string(),"丑".to_string()),("廚".to_string(),"厨".to_string()),("櫥".to_string(),"橱".to_string()),("鋤".to_string(),"锄".to_string()),("雛".to_string(),"雏".to_string()),("儲".to_string(),"储".to_string()),("処".to_string(),"处".to_string()),("礎".to_string(),"础".to_string()),("伝".to_string(),"传".to_string()),("創".to_string(),"创".to_string()),("闖".to_string(),"闯".to_string()),("瘡".to_string(),"疮".to_string()),("錘".to_string(),"锤".to_string()),("純".to_string(),"纯".to_string()),("綽".to_string(),"绰".to_string()),("詞".to_string(),"词".to_string()),("賜".to_string(),"赐".to_string()),("叢".to_string(),"丛".to_string()),("蔥".to_string(),"葱".to_string()),("従".to_string(),"从".to_string()),("囪".to_string(),"囱".to_string()),("聰".to_string(),"聪".to_string()),("湊".to_string(),"凑".to_string()),("竄".to_string(),"窜".to_string()),("錯".to_string(),"错".to_string()),("達".to_string(),"达".to_string()),("帯".to_string(),"带".to_string()),("貸".to_string(),"贷".to_string()),("弾".to_string(),"弹".to_string()),("誕".to_string(),"诞".to_string()),("撣".to_string(),"掸".to_string()),("単".to_string(),"单".to_string()),("檔".to_string(),"档".to_string()),("蕩".to_string(),"荡".to_string()),("擋".to_string(),"挡".to_string()),("禱".to_string(),"祷".to_string()),("導".to_string(),"导".to_string()),("島".to_string(),"岛".to_string()),("搗".to_string(),"捣".to_string()),("鄧".to_string(),"邓".to_string()),("敵".to_string(),"敌".to_string()),("滌".to_string(),"涤".to_string()),("締".to_string(),"缔".to_string()),("逓".to_string(),"递".to_string()),("澱".to_string(),"淀".to_string()),("墊".to_string(),"垫".to_string()),("電".to_string(),"电".to_string()),("顛".to_string(),"颠".to_string()),("調".to_string(),"调".to_string()),("釣".to_string(),"钓".to_string()),("畳".to_string(),"叠".to_string()),("諜".to_string(),"谍".to_string()),("訂".to_string(),"订".to_string()),("釘".to_string(),"钉".to_string()),("錠".to_string(),"锭".to_string()),("頂".to_string(),"顶".to_string()),("丟".to_string(),"丢".to_string()),("凍".to_string(),"冻".to_string()),("働".to_string(),"动".to_string()),("東".to_string(),"东".to_string()),("読".to_string(),"读".to_string()),("鍍".to_string(),"镀".to_string()),("賭".to_string(),"赌".to_string()),("緞".to_string(),"缎".to_string()),("鍛".to_string(),"锻".to_string()),("兌".to_string(),"兑".to_string()),("対".to_string(),"对".to_string()),("隊".to_string(),"队".to_string()),("鈍".to_string(),"钝".to_string()),("頓".to_string(),"顿".to_string()),("噸".to_string(),"吨".to_string()),("奪".to_string(),"夺".to_string()),("訛".to_string(),"讹".to_string()),("額".to_string(),"额".to_string()),("鵝".to_string(),"鹅".to_string()),("悪".to_string(),"恶".to_string()),("餓".to_string(),"饿".to_string()),("児".to_string(),"儿".to_string()),("弐".to_string(),"贰".to_string()),("爾".to_string(),"尔".to_string()),("餌".to_string(),"饵".to_string()),("誹".to_string(),"诽".to_string()),("罰".to_string(),"罚".to_string()),("閥".to_string(),"阀".to_string()),("発".to_string(),"发".to_string()),("髪".to_string(),"发".to_string()),("煩".to_string(),"烦".to_string()),("礬".to_string(),"矾".to_string()),("範".to_string(),"范".to_string()),("販".to_string(),"贩".to_string()),("飯".to_string(),"饭".to_string()),("紡".to_string(),"纺".to_string()),("訪".to_string(),"访".to_string()),("廃".to_string(),"废".to_string()),("費".to_string(),"费".to_string()),("飛".to_string(),"飞".to_string()),("墳".to_string(),"坟".to_string()),("奮".to_string(),"奋".to_string()),("憤".to_string(),"愤".to_string()),("糞".to_string(),"粪".to_string()),("紛".to_string(),"纷".to_string()),("馮".to_string(),"冯".to_string()),("縫".to_string(),"缝".to_string()),("鳳".to_string(),"凤".to_string()),("諷".to_string(),"讽".to_string()),("豊".to_string(),"丰".to_string()),("楓".to_string(),"枫".to_string()),("瘋".to_string(),"疯".to_string()),("鋒".to_string(),"锋".to_string()),("風".to_string(),"风".to_string()),("輻".to_string(),"辐".to_string()),("復".to_string(),"复".to_string()),("複".to_string(),"复".to_string()),("婦".to_string(),"妇".to_string()),("縛".to_string(),"缚".to_string()),("負".to_string(),"负".to_string()),("賦".to_string(),"赋".to_string()),("撫".to_string(),"抚".to_string()),("輔".to_string(),"辅".to_string()),("膚".to_string(),"肤".to_string()),("蓋".to_string(),"盖".to_string()),("鈣".to_string(),"钙".to_string()),("該".to_string(),"该".to_string()),("趕".to_string(),"赶".to_string()),("稈".to_string(),"秆".to_string()),("崗".to_string(),"岗".to_string()),("岡".to_string(),"冈".to_string()),("剛".to_string(),"刚".to_string()),("綱".to_string(),"纲".to_string()),("鋼".to_string(),"钢".to_string()),("鎬".to_string(),"镐".to_string()),("閣".to_string(),"阁".to_string()),("個".to_string(),"个".to_string()),("箇".to_string(),"个".to_string()),("擱".to_string(),"搁".to_string()),("鴿".to_string(),"鸽".to_string()),("給".to_string(),"给".to_string()),("貢".to_string(),"贡".to_string()),("鞏".to_string(),"巩".to_string()),("宮".to_string(),"宫".to_string()),("夠".to_string(),"够".to_string()),("構".to_string(),"构".to_string()),("購".to_string(),"购".to_string()),("溝".to_string(),"沟".to_string()),("鈎".to_string(),"钩".to_string()),("顧".to_string(),"顾".to_string()),("慣".to_string(),"惯".to_string()),("貫".to_string(),"贯".to_string()),("館".to_string(),"馆".to_string()),("関".to_string(),"关".to_string()),("観".to_string(),"观".to_string()),("広".to_string(),"广".to_string()),("劊".to_string(),"刽".to_string()),("櫃".to_string(),"柜".to_string()),("貴".to_string(),"贵".to_string()),("詭".to_string(),"诡".to_string()),("軌".to_string(),"轨".to_string()),("矽".to_string(),"硅".to_string()),("帰".to_string(),"归".to_string()),("規".to_string(),"规".to_string()),("閨".to_string(),"闺".to_string()),("龜".to_string(),"龟".to_string()),("滾".to_string(),"滚".to_string()),("過".to_string(),"过".to_string()),("鍋".to_string(),"锅".to_string()),("還".to_string(),"还".to_string()),("駭".to_string(),"骇".to_string()),("韓".to_string(),"韩".to_string()),("漢".to_string(),"汉".to_string()),("賀".to_string(),"贺".to_string()),("鶴".to_string(),"鹤".to_string()),("紅".to_string(),"红".to_string()),("鴻".to_string(),"鸿".to_string()),("轟".to_string(),"轰".to_string()),("後".to_string(),"后".to_string()),("壺".to_string(),"壶".to_string()),("戸".to_string(),"户".to_string()),("護".to_string(),"护".to_string()),("滬".to_string(),"沪".to_string()),("華".to_string(),"华".to_string()),("嘩".to_string(),"哗".to_string()),("劃".to_string(),"划".to_string()),("話".to_string(),"话".to_string()),("懐".to_string(),"怀".to_string()),("壊".to_string(),"坏".to_string()),("環".to_string(),"环".to_string()),("喚".to_string(),"唤".to_string()),("換".to_string(),"换".to_string()),("渙".to_string(),"涣".to_string()),("煥".to_string(),"焕".to_string()),("瘓".to_string(),"痪".to_string()),("緩".to_string(),"缓".to_string()),("歓".to_string(),"欢".to_string()),("謊".to_string(),"谎".to_string()),("彙".to_string(),"汇".to_string()),("穢".to_string(),"秽".to_string()),("絵".to_string(),"绘".to_string()),("諱".to_string(),"讳".to_string()),("誨".to_string(),"诲".to_string()),("賄".to_string(),"贿".to_string()),("毀".to_string(),"毁".to_string()),("揮".to_string(),"挥".to_string()),("輝".to_string(),"辉".to_string()),("渾".to_string(),"浑".to_string()),("葷".to_string(),"荤".to_string()),("禍".to_string(),"祸".to_string()),("獲".to_string(),"获".to_string()),("貨".to_string(),"货".to_string()),("夥".to_string(),"伙".to_string()),("極".to_string(),"极".to_string()),("級".to_string(),"级".to_string()),("輯".to_string(),"辑".to_string()),("剤".to_string(),"剂".to_string()),("済".to_string(),"济".to_string()),("紀".to_string(),"纪".to_string()),("継".to_string(),"继".to_string()),("計".to_string(),"计".to_string()),("記".to_string(),"记".to_string()),("際".to_string(),"际".to_string()),("幾".to_string(),"几".to_string()),("擠".to_string(),"挤".to_string()),("機".to_string(),"机".to_string()),("机".to_string(),"机".to_string()),("撃".to_string(),"击".to_string()),("積".to_string(),"积".to_string()),("績".to_string(),"绩".to_string()),("譏".to_string(),"讥".to_string()),("飢".to_string(),"饥".to_string()),("鶏".to_string(),"鸡".to_string()),("莢".to_string(),"荚".to_string()),("頰".to_string(),"颊".to_string()),("価".to_string(),"价".to_string()),("駕".to_string(),"驾".to_string()),("賈".to_string(),"贾".to_string()),("鉀".to_string(),"钾".to_string()),("夾".to_string(),"夹".to_string()),("薦".to_string(),"荐".to_string()),("剣".to_string(),"剑".to_string()),("澗".to_string(),"涧".to_string()),("漸".to_string(),"渐".to_string()),("濺".to_string(),"溅".to_string()),("艦".to_string(),"舰".to_string()),("見".to_string(),"见".to_string()),("賤".to_string(),"贱".to_string()),("鑑".to_string(),"鉴".to_string()),("鍵".to_string(),"键".to_string()),("倹".to_string(),"俭".to_string()),("減".to_string(),"减".to_string()),("揀".to_string(),"拣".to_string()),("撿".to_string(),"捡".to_string()),("検".to_string(),"检".to_string()),("堿".to_string(),"碱".to_string()),("簡".to_string(),"简".to_string()),("繭".to_string(),"茧".to_string()),("堅".to_string(),"坚".to_string()),("殲".to_string(),"歼".to_string()),("監".to_string(),"监".to_string()),("艱".to_string(),"艰".to_string()),("間".to_string(),"间".to_string()),("醬".to_string(),"酱".to_string()),("蔣".to_string(),"蒋".to_string()),("奨".to_string(),"奖".to_string()),("槳".to_string(),"桨".to_string()),("講".to_string(),"讲".to_string()),("漿".to_string(),"浆".to_string()),("轎".to_string(),"轿".to_string()),("較".to_string(),"较".to_string()),("僥".to_string(),"侥".to_string()),("攪".to_string(),"搅".to_string()),("矯".to_string(),"矫".to_string()),("絞".to_string(),"绞".to_string()),("繳".to_string(),"缴".to_string()),("餃".to_string(),"饺".to_string()),("嬌".to_string(),"娇".to_string()),("澆".to_string(),"浇".to_string()),("膠".to_string(),"胶".to_string()),("驕".to_string(),"骄".to_string()),("傑".to_string(),"杰".to_string()),("潔".to_string(),"洁".to_string()),("結".to_string(),"结".to_string()),("節".to_string(),"节".to_string()),("誡".to_string(),"诫".to_string()),("稭".to_string(),"秸".to_string()),("階".to_string(),"阶".to_string()),("晉".to_string(),"晋".to_string()),("勁".to_string(),"劲".to_string()),("進".to_string(),"进".to_string()),("僅".to_string(),"仅".to_string()),("緊".to_string(),"紧".to_string()),("謹".to_string(),"谨".to_string()),("錦".to_string(),"锦".to_string()),("荊".to_string(),"荆".to_string()),("浄".to_string(),"净".to_string()),("競".to_string(),"竞".to_string()),("鏡".to_string(),"镜".to_string()),("頸".to_string(),"颈".to_string()),("驚".to_string(),"惊".to_string()),("経".to_string(),"经".to_string()),("鯨".to_string(),"鲸".to_string()),("糾".to_string(),"纠".to_string()),("拠".to_string(),"据".to_string()),("懼".to_string(),"惧".to_string()),("劇".to_string(),"剧".to_string()),("鋸".to_string(),"锯".to_string()),("挙".to_string(),"举".to_string()),("駒".to_string(),"驹".to_string()),("絹".to_string(),"绢".to_string()),("鵑".to_string(),"鹃".to_string()),("決".to_string(),"决".to_string()),("絶".to_string(),"绝".to_string()),("覚".to_string(),"觉".to_string()),("訣".to_string(),"诀".to_string()),("駿".to_string(),"骏".to_string()),("軍".to_string(),"军".to_string()),("鈞".to_string(),"钧".to_string()),("凱".to_string(),"凯".to_string()),("開".to_string(),"开".to_string()),("殻".to_string(),"壳".to_string()),("課".to_string(),"课".to_string()),("顆".to_string(),"颗".to_string()),("墾".to_string(),"垦".to_string()),("懇".to_string(),"恳".to_string()),("摳".to_string(),"抠".to_string()),("庫".to_string(),"库".to_string()),("褲".to_string(),"裤".to_string()),("誇".to_string(),"夸".to_string()),("塊".to_string(),"块".to_string()),("寛".to_string(),"宽".to_string()),("況".to_string(),"况".to_string()),("曠".to_string(),"旷".to_string()),("鉱".to_string(),"矿".to_string()),("潰".to_string(),"溃".to_string()),("虧".to_string(),"亏".to_string()),("窺".to_string(),"窥".to_string()),("拡".to_string(),"扩".to_string()),("闊".to_string(),"阔".to_string()),("臘".to_string(),"腊".to_string()),("蠟".to_string(),"蜡".to_string()),("萊".to_string(),"莱".to_string()),("頼".to_string(),"赖".to_string()),("蘭".to_string(),"兰".to_string()),("攔".to_string(),"拦".to_string()),("欄".to_string(),"栏".to_string()),("瀾".to_string(),"澜".to_string()),("籃".to_string(),"篮".to_string()),("藍".to_string(),"蓝".to_string()),("濫".to_string(),"滥".to_string()),("爛".to_string(),"烂".to_string()),("懶".to_string(),"懒".to_string()),("攬".to_string(),"揽".to_string()),("纜".to_string(),"缆".to_string()),("覧".to_string(),"览".to_string()),("労".to_string(),"劳".to_string()),("澇".to_string(),"涝".to_string()),("撈".to_string(),"捞".to_string()),("楽".to_string(),"乐".to_string()),("涙".to_string(),"泪".to_string()),("類".to_string(),"类".to_string()),("塁".to_string(),"垒".to_string()),("離".to_string(),"离".to_string()),("籬".to_string(),"篱".to_string()),("隷".to_string(),"隶".to_string()),("麗".to_string(),"丽".to_string()),("暦".to_string(),"历".to_string()),("厲".to_string(),"厉".to_string()),("瀝".to_string(),"沥".to_string()),("礫".to_string(),"砾".to_string()),("鯉".to_string(),"鲤".to_string()),("憐".to_string(),"怜".to_string()),("簾".to_string(),"帘".to_string()),("聯".to_string(),"联".to_string()),("蓮".to_string(),"莲".to_string()),("連".to_string(),"连".to_string()),("鐮".to_string(),"镰".to_string()),("錬".to_string(),"炼".to_string()),("練".to_string(),"练".to_string()),("鏈".to_string(),"链".to_string()),("斂".to_string(),"敛".to_string()),("臉".to_string(),"脸".to_string()),("涼".to_string(),"凉".to_string()),("糧".to_string(),"粮".to_string()),("諒".to_string(),"谅".to_string()),("輛".to_string(),"辆".to_string()),("両".to_string(),"两".to_string()),("倆".to_string(),"俩".to_string()),("療".to_string(),"疗".to_string()),("遼".to_string(),"辽".to_string()),("鐐".to_string(),"镣".to_string()),("猟".to_string(),"猎".to_string()),("臨".to_string(),"临".to_string()),("隣".to_string(),"邻".to_string()),("鱗".to_string(),"鳞".to_string()),("賃".to_string(),"赁".to_string()),("凜".to_string(),"凛".to_string()),("淩".to_string(),"凌".to_string()),("霊".to_string(),"灵".to_string()),("鈴".to_string(),"铃".to_string()),("齢".to_string(),"龄".to_string()),("嶺".to_string(),"岭".to_string()),("領".to_string(),"领".to_string()),("劉".to_string(),"刘".to_string()),("餾".to_string(),"馏".to_string()),("嚨".to_string(),"咙".to_string()),("籠".to_string(),"笼".to_string()),("聾".to_string(),"聋".to_string()),("竜".to_string(),"龙".to_string()),("壟".to_string(),"垄".to_string()),("攏".to_string(),"拢".to_string()),("婁".to_string(),"娄".to_string()),("摟".to_string(),"搂".to_string()),("簍".to_string(),"篓".to_string()),("蘆".to_string(),"芦".to_string()),("盧".to_string(),"卢".to_string()),("廬".to_string(),"庐".to_string()),("顱".to_string(),"颅".to_string()),("録".to_string(),"录".to_string()),("賂".to_string(),"赂".to_string()),("陸".to_string(),"陆".to_string()),("鹵".to_string(),"卤".to_string()),("虜".to_string(),"虏".to_string()),("魯".to_string(),"鲁".to_string()),("驢".to_string(),"驴".to_string()),("濾".to_string(),"滤".to_string()),("緑".to_string(),"绿".to_string()),("慮".to_string(),"虑".to_string()),("屢".to_string(),"屡".to_string()),("侶".to_string(),"侣".to_string()),("呂".to_string(),"吕".to_string()),("縷".to_string(),"缕".to_string()),("鋁".to_string(),"铝".to_string()),("巒".to_string(),"峦".to_string()),("侖".to_string(),"仑".to_string()),("倫".to_string(),"伦".to_string()),("掄".to_string(),"抡".to_string()),("淪".to_string(),"沦".to_string()),("輪".to_string(),"轮".to_string()),("論".to_string(),"论".to_string()),("籮".to_string(),"箩".to_string()),("羅".to_string(),"罗".to_string()),("蘿".to_string(),"萝".to_string()),("邏".to_string(),"逻".to_string()),("鑼".to_string(),"锣".to_string()),("騾".to_string(),"骡".to_string()),("絡".to_string(),"络".to_string()),("駱".to_string(),"骆".to_string()),("嗎".to_string(),"吗".to_string()),("罵".to_string(),"骂".to_string()),("碼".to_string(),"码".to_string()),("螞".to_string(),"蚂".to_string()),("馬".to_string(),"马".to_string()),("媽".to_string(),"妈".to_string()),("脈".to_string(),"脉".to_string()),("売".to_string(),"卖".to_string()),("邁".to_string(),"迈".to_string()),("買".to_string(),"买".to_string()),("瞞".to_string(),"瞒".to_string()),("饅".to_string(),"馒".to_string()),("満".to_string(),"满".to_string()),("錨".to_string(),"锚".to_string()),("貿".to_string(),"贸".to_string()),("鉚".to_string(),"铆".to_string()),("麽".to_string(),"么".to_string()),("黴".to_string(),"霉".to_string()),("們".to_string(),"们".to_string()),("門".to_string(),"门".to_string()),("悶".to_string(),"闷".to_string()),("夢".to_string(),"梦".to_string()),("錳".to_string(),"锰".to_string()),("彌".to_string(),"弥".to_string()),("謎".to_string(),"谜".to_string()),("覓".to_string(),"觅".to_string()),("綿".to_string(),"绵".to_string()),("緬".to_string(),"缅".to_string()),("廟".to_string(),"庙".to_string()),("滅".to_string(),"灭".to_string()),("憫".to_string(),"悯".to_string()),("閩".to_string(),"闽".to_string()),("銘".to_string(),"铭".to_string()),("鳴".to_string(),"鸣".to_string()),("謬".to_string(),"谬".to_string()),("謀".to_string(),"谋".to_string()),("畝".to_string(),"亩".to_string()),("納".to_string(),"纳".to_string()),("鈉".to_string(),"钠".to_string()),("難".to_string(),"难".to_string()),("撓".to_string(),"挠".to_string()),("鬧".to_string(),"闹".to_string()),("悩".to_string(),"恼".to_string()),("脳".to_string(),"脑".to_string()),("餒".to_string(),"馁".to_string()),("膩".to_string(),"腻".to_string()),("妳".to_string(),"你".to_string()),("擬".to_string(),"拟".to_string()),("撚".to_string(),"捻".to_string()),("攆".to_string(),"撵".to_string()),("醸".to_string(),"酿".to_string()),("鳥".to_string(),"鸟".to_string()),("聶".to_string(),"聂".to_string()),("鑷".to_string(),"镊".to_string()),("寧".to_string(),"宁".to_string()),("擰".to_string(),"拧".to_string()),("檸".to_string(),"柠".to_string()),("獰".to_string(),"狞".to_string()),("濘".to_string(),"泞".to_string()),("紐".to_string(),"纽".to_string()),("鈕".to_string(),"钮".to_string()),("農".to_string(),"农".to_string()),("濃".to_string(),"浓".to_string()),("膿".to_string(),"脓".to_string()),("瘧".to_string(),"疟".to_string()),("諾".to_string(),"诺".to_string()),("嘔".to_string(),"呕".to_string()),("鷗".to_string(),"鸥".to_string()),("盤".to_string(),"盘".to_string()),("龐".to_string(),"庞".to_string()),("賠".to_string(),"赔".to_string()),("噴".to_string(),"喷".to_string()),("鵬".to_string(),"鹏".to_string()),("騙".to_string(),"骗".to_string()),("飄".to_string(),"飘".to_string()),("貧".to_string(),"贫".to_string()),("頻".to_string(),"频".to_string()),("憑".to_string(),"凭".to_string()),("蘋".to_string(),"苹".to_string()),("評".to_string(),"评".to_string()),("潑".to_string(),"泼".to_string()),("頗".to_string(),"颇".to_string()),("舗".to_string(),"铺".to_string()),("樸".to_string(),"朴".to_string()),("譜".to_string(),"谱".to_string()),("撲".to_string(),"扑".to_string()),("臍".to_string(),"脐".to_string()),("騎".to_string(),"骑".to_string()),("斉".to_string(),"齐".to_string()),("棄".to_string(),"弃".to_string()),("気".to_string(),"气".to_string()),("啓".to_string(),"启".to_string()),("豈".to_string(),"岂".to_string()),("淒".to_string(),"凄".to_string()),("棲".to_string(),"栖".to_string()),("銭".to_string(),"钱".to_string()),("鉗".to_string(),"钳".to_string()),("譴".to_string(),"谴".to_string()),("牽".to_string(),"牵".to_string()),("簽".to_string(),"签".to_string()),("謙".to_string(),"谦".to_string()),("遷".to_string(),"迁".to_string()),("鉛".to_string(),"铅".to_string()),("牆".to_string(),"墙".to_string()),("強".to_string(),"强".to_string()),("搶".to_string(),"抢".to_string()),("嗆".to_string(),"呛".to_string()),("槍".to_string(),"枪".to_string()),("喬".to_string(),"乔".to_string()),("僑".to_string(),"侨".to_string()),("橋".to_string(),"桥".to_string()),("竅".to_string(),"窍".to_string()),("翹".to_string(),"翘".to_string()),("鍬".to_string(),"锹".to_string()),("親".to_string(),"亲".to_string()),("欽".to_string(),"钦".to_string()),("慶".to_string(),"庆".to_string()),("請".to_string(),"请".to_string()),("頃".to_string(),"顷".to_string()),("傾".to_string(),"倾".to_string()),("氫".to_string(),"氢".to_string()),("軽".to_string(),"轻".to_string()),("瓊".to_string(),"琼".to_string()),("窮".to_string(),"穷".to_string()),("軀".to_string(),"躯".to_string()),("趨".to_string(),"趋".to_string()),("駆".to_string(),"驱".to_string()),("権".to_string(),"权".to_string()),("勧".to_string(),"劝".to_string()),("確".to_string(),"确".to_string()),("鵲".to_string(),"鹊".to_string()),("譲".to_string(),"让".to_string()),("饒".to_string(),"饶".to_string()),("繞".to_string(),"绕".to_string()),("擾".to_string(),"扰".to_string()),("熱".to_string(),"热".to_string()),("紉".to_string(),"纫".to_string()),("認".to_string(),"认".to_string()),("韌".to_string(),"韧".to_string()),("絨".to_string(),"绒".to_string()),("栄".to_string(),"荣".to_string()),("軟".to_string(),"软".to_string()),("鋭".to_string(),"锐".to_string()),("潤".to_string(),"润".to_string()),("閏".to_string(),"闰".to_string()),("薩".to_string(),"萨".to_string()),("灑".to_string(),"洒".to_string()),("賽".to_string(),"赛".to_string()),("傘".to_string(),"伞".to_string()),("三".to_string(),"叁".to_string()),("喪".to_string(),"丧".to_string()),("掃".to_string(),"扫".to_string()),("騒".to_string(),"骚".to_string()),("渋".to_string(),"涩".to_string()),("殺".to_string(),"杀".to_string()),("紗".to_string(),"纱".to_string()),("曬".to_string(),"晒".to_string()),("篩".to_string(),"筛".to_string()),("贍".to_string(),"赡".to_string()),("閃".to_string(),"闪".to_string()),("陝".to_string(),"陕".to_string()),("刪".to_string(),"删".to_string()),("賞".to_string(),"赏".to_string()),("傷".to_string(),"伤".to_string()),("紹".to_string(),"绍".to_string()),("焼".to_string(),"烧".to_string()),("摂".to_string(),"摄".to_string()),("設".to_string(),"设".to_string()),("賒".to_string(),"赊".to_string()),("嬸".to_string(),"婶".to_string()),("審".to_string(),"审".to_string()),("滲".to_string(),"渗".to_string()),("腎".to_string(),"肾".to_string()),("紳".to_string(),"绅".to_string()),("縄".to_string(),"绳".to_string()),("聖".to_string(),"圣".to_string()),("勝".to_string(),"胜".to_string()),("実".to_string(),"实".to_string()),("時".to_string(),"时".to_string()),("蝕".to_string(),"蚀".to_string()),("識".to_string(),"识".to_string()),("勢".to_string(),"势".to_string()),("視".to_string(),"视".to_string()),("試".to_string(),"试".to_string()),("適".to_string(),"适".to_string()),("釈".to_string(),"释".to_string()),("飾".to_string(),"饰".to_string()),("駛".to_string(),"驶".to_string()),("屍".to_string(),"尸".to_string()),("師".to_string(),"师".to_string()),("獅".to_string(),"狮".to_string()),("詩".to_string(),"诗".to_string()),("獣".to_string(),"兽".to_string()),("贖".to_string(),"赎".to_string()),("術".to_string(),"术".to_string()),("樹".to_string(),"树".to_string()),("豎".to_string(),"竖".to_string()),("書".to_string(),"书".to_string()),("輸".to_string(),"输".to_string()),("帥".to_string(),"帅".to_string()),("誰".to_string(),"谁".to_string()),("順".to_string(),"顺".to_string()),("爍".to_string(),"烁".to_string()),("碩".to_string(),"硕".to_string()),("説".to_string(),"说".to_string()),("飼".to_string(),"饲".to_string()),("絲".to_string(),"丝".to_string()),("訟".to_string(),"讼".to_string()),("誦".to_string(),"诵".to_string()),("頌".to_string(),"颂".to_string()),("聳".to_string(),"耸".to_string()),("粛".to_string(),"肃".to_string()),("訴".to_string(),"诉".to_string()),("蘇".to_string(),"苏".to_string()),("歳".to_string(),"岁".to_string()),("雖".to_string(),"虽".to_string()),("筍".to_string(),"笋".to_string()),("損".to_string(),"损".to_string()),("孫".to_string(),"孙".to_string()),("瑣".to_string(),"琐".to_string()),("鎖".to_string(),"锁".to_string()),("縮".to_string(),"缩".to_string()),("擡".to_string(),"抬".to_string()),("態".to_string(),"态".to_string()),("壇".to_string(),"坛".to_string()),("談".to_string(),"谈".to_string()),("譚".to_string(),"谭".to_string()),("嘆".to_string(),"叹".to_string()),("攤".to_string(),"摊".to_string()),("灘".to_string(),"滩".to_string()),("癱".to_string(),"瘫".to_string()),("貪".to_string(),"贪".to_string()),("燙".to_string(),"烫".to_string()),("湯".to_string(),"汤".to_string()),("討".to_string(),"讨".to_string()),("濤".to_string(),"涛".to_string()),("騰".to_string(),"腾".to_string()),("謄".to_string(),"誊".to_string()),("題".to_string(),"题".to_string()),("屜".to_string(),"屉".to_string()),("鉄".to_string(),"铁".to_string()),("貼".to_string(),"贴".to_string()),("聴".to_string(),"听".to_string()),("庁".to_string(),"厅".to_string()),("銅".to_string(),"铜".to_string()),("統".to_string(),"统".to_string()),("頭".to_string(),"头".to_string()),("図".to_string(),"图".to_string()),("塗".to_string(),"涂".to_string()),("禿".to_string(),"秃".to_string()),("団".to_string(),"团".to_string()),("頹".to_string(),"颓".to_string()),("蛻".to_string(),"蜕".to_string()),("駄".to_string(),"驮".to_string()),("駝".to_string(),"驼".to_string()),("鴕".to_string(),"鸵".to_string()),("橢".to_string(),"椭".to_string()),("襪".to_string(),"袜".to_string()),("窪".to_string(),"洼".to_string()),("頑".to_string(),"顽".to_string()),("彎".to_string(),"弯".to_string()),("網".to_string(),"网".to_string()),("為".to_string(),"为".to_string()),("囲".to_string(),"围".to_string()),("維".to_string(),"维".to_string()),("違".to_string(),"违".to_string()),("衛".to_string(),"卫".to_string()),("謂".to_string(),"谓".to_string()),("偉".to_string(),"伟".to_string()),("偽".to_string(),"伪".to_string()),("緯".to_string(),"纬".to_string()),("葦".to_string(),"苇".to_string()),("紋".to_string(),"纹".to_string()),("聞".to_string(),"闻".to_string()),("問".to_string(),"问".to_string()),("穏".to_string(),"稳".to_string()),("甕".to_string(),"瓮".to_string()),("臥".to_string(),"卧".to_string()),("渦".to_string(),"涡".to_string()),("窩".to_string(),"窝".to_string()),("蝸".to_string(),"蜗".to_string()),("無".to_string(),"无".to_string()),("呉".to_string(),"吴".to_string()),("蕪".to_string(),"芜".to_string()),("務".to_string(),"务".to_string()),("塢".to_string(),"坞".to_string()),("誤".to_string(),"误".to_string()),("霧".to_string(),"雾".to_string()),("烏".to_string(),"乌".to_string()),("嗚".to_string(),"呜".to_string()),("汚".to_string(),"污".to_string()),("誣".to_string(),"诬".to_string()),("習".to_string(),"习".to_string()),("襲".to_string(),"袭".to_string()),("系".to_string(),"系".to_string()),("係".to_string(),"系".to_string()),("戯".to_string(),"戏".to_string()),("細".to_string(),"细".to_string()),("銑".to_string(),"铣".to_string()),("犠".to_string(),"牺".to_string()),("錫".to_string(),"锡".to_string()),("俠".to_string(),"侠".to_string()),("轄".to_string(),"辖".to_string()),("廈".to_string(),"厦".to_string()),("嚇".to_string(),"吓".to_string()),("蝦".to_string(),"虾".to_string()),("鹹".to_string(),"咸".to_string()),("銜".to_string(),"衔".to_string()),("賢".to_string(),"贤".to_string()),("閑".to_string(),"闲".to_string()),("羨".to_string(),"羡".to_string()),("県".to_string(),"县".to_string()),("憲".to_string(),"宪".to_string()),("現".to_string(),"现".to_string()),("線".to_string(),"线".to_string()),("餡".to_string(),"馅".to_string()),("顕".to_string(),"显".to_string()),("険".to_string(),"险".to_string()),("繊".to_string(),"纤".to_string()),("鍁".to_string(),"锨".to_string()),("鮮".to_string(),"鲜".to_string()),("詳".to_string(),"详".to_string()),("項".to_string(),"项".to_string()),("響".to_string(),"响".to_string()),("郷".to_string(),"乡".to_string()),("廂".to_string(),"厢".to_string()),("鑲".to_string(),"镶".to_string()),("嘯".to_string(),"啸".to_string()),("暁".to_string(),"晓".to_string()),("囂".to_string(),"嚣".to_string()),("蕭".to_string(),"萧".to_string()),("銷".to_string(),"销".to_string()),("協".to_string(),"协".to_string()),("脅".to_string(),"胁".to_string()),("諧".to_string(),"谐".to_string()),("潟".to_string(),"泻".to_string()),("謝".to_string(),"谢".to_string()),("蠍".to_string(),"蝎".to_string()),("釁".to_string(),"衅".to_string()),("鋅".to_string(),"锌".to_string()),("興".to_string(),"兴".to_string()),("洶".to_string(),"汹".to_string()),("繡".to_string(),"绣".to_string()),("鏽".to_string(),"锈".to_string()),("緒".to_string(),"绪".to_string()),("続".to_string(),"续".to_string()),("軒".to_string(),"轩".to_string()),("許".to_string(),"许".to_string()),("須".to_string(),"须".to_string()),("懸".to_string(),"悬".to_string()),("癬".to_string(),"癣".to_string()),("選".to_string(),"选".to_string()),("尋".to_string(),"寻".to_string()),("詢".to_string(),"询".to_string()),("馴".to_string(),"驯".to_string()),("訓".to_string(),"训".to_string()),("訊".to_string(),"讯".to_string()),("遜".to_string(),"逊".to_string()),("勲".to_string(),"勋".to_string()),("亜".to_string(),"亚".to_string()),("訝".to_string(),"讶".to_string()),("啞".to_string(),"哑".to_string()),("圧".to_string(),"压".to_string()),("鴉".to_string(),"鸦".to_string()),("鴨".to_string(),"鸭".to_string()),("厳".to_string(),"严".to_string()),("塩".to_string(),"盐".to_string()),("閻".to_string(),"阎".to_string()),("顔".to_string(),"颜".to_string()),("厭".to_string(),"厌".to_string()),("硯".to_string(),"砚".to_string()),("豔".to_string(),"艳".to_string()),("諺".to_string(),"谚".to_string()),("験".to_string(),"验".to_string()),("煙".to_string(),"烟".to_string()),("揚".to_string(),"扬".to_string()),("楊".to_string(),"杨".to_string()),("陽".to_string(),"阳".to_string()),("様".to_string(),"样".to_string()),("癢".to_string(),"痒".to_string()),("養".to_string(),"养".to_string()),("鴦".to_string(),"鸯".to_string()),("遙".to_string(),"遥".to_string()),("揺".to_string(),"摇".to_string()),("窯".to_string(),"窑".to_string()),("謡".to_string(),"谣".to_string()),("薬".to_string(),"药".to_string()),("鑰".to_string(),"钥".to_string()),("爺".to_string(),"爷".to_string()),("葉".to_string(),"叶".to_string()),("業".to_string(),"业".to_string()),("頁".to_string(),"页".to_string()),("儀".to_string(),"仪".to_string()),("遺".to_string(),"遗".to_string()),("義".to_string(),"义".to_string()),("億".to_string(),"亿".to_string()),("異".to_string(),"异".to_string()),("憶".to_string(),"忆".to_string()),("繹".to_string(),"绎".to_string()),("芸".to_string(),"艺".to_string()),("議".to_string(),"议".to_string()),("訳".to_string(),"译".to_string()),("誼".to_string(),"谊".to_string()),("蟻".to_string(),"蚁".to_string()),("銀".to_string(),"银".to_string()),("隠".to_string(),"隐".to_string()),("飲".to_string(),"饮".to_string()),("陰".to_string(),"阴".to_string()),("熒".to_string(),"荧".to_string()),("瑩".to_string(),"莹".to_string()),("蛍".to_string(),"萤".to_string()),("営".to_string(),"营".to_string()),("蠅".to_string(),"蝇".to_string()),("贏".to_string(),"赢".to_string()),("穎".to_string(),"颖".to_string()),("嬰".to_string(),"婴".to_string()),("応".to_string(),"应".to_string()),("桜".to_string(),"樱".to_string()),("纓".to_string(),"缨".to_string()),("鷹".to_string(),"鹰".to_string()),("喲".to_string(),"哟".to_string()),("湧".to_string(),"涌".to_string()),("詠".to_string(),"咏".to_string()),("傭".to_string(),"佣".to_string()),("擁".to_string(),"拥".to_string()),("遊".to_string(),"游".to_string()),("猶".to_string(),"犹".to_string()),("郵".to_string(),"邮".to_string()),("誘".to_string(),"诱".to_string()),("優".to_string(),"优".to_string()),("憂".to_string(),"忧".to_string()),("娯".to_string(),"娱".to_string()),("漁".to_string(),"渔".to_string()),("輿".to_string(),"舆".to_string()),("魚".to_string(),"鱼".to_string()),("籲".to_string(),"吁".to_string()),("獄".to_string(),"狱".to_string()),("預".to_string(),"预".to_string()),("嶼".to_string(),"屿".to_string()),("語".to_string(),"语".to_string()),("員".to_string(),"员".to_string()),("園".to_string(),"园".to_string()),("円".to_string(),"圆".to_string()),("縁".to_string(),"缘".to_string()),("轅".to_string(),"辕".to_string()),("願".to_string(),"愿".to_string()),("遠".to_string(),"远".to_string()),("淵".to_string(),"渊".to_string()),("鴛".to_string(),"鸳".to_string()),("粵".to_string(),"粤".to_string()),("躍".to_string(),"跃".to_string()),("閲".to_string(),"阅".to_string()),("約".to_string(),"约".to_string()),("雲".to_string(),"云".to_string()),("勻".to_string(),"匀".to_string()),("韻".to_string(),"韵".to_string()),("蘊".to_string(),"蕴".to_string()),("運".to_string(),"运".to_string()),("醞".to_string(),"酝".to_string()),("隕".to_string(),"陨".to_string()),("暈".to_string(),"晕".to_string()),("雑".to_string(),"杂".to_string()),("載".to_string(),"载".to_string()),("災".to_string(),"灾".to_string()),("暫".to_string(),"暂".to_string()),("賛".to_string(),"赞".to_string()),("攢".to_string(),"攒".to_string()),("臓".to_string(),"脏".to_string()),("贓".to_string(),"赃".to_string()),("鑿".to_string(),"凿".to_string()),("竈".to_string(),"灶".to_string()),("棗".to_string(),"枣".to_string()),("則".to_string(),"则".to_string()),("択".to_string(),"择".to_string()),("沢".to_string(),"泽".to_string()),("責".to_string(),"责".to_string()),("賊".to_string(),"贼".to_string()),("贈".to_string(),"赠".to_string()),("軋".to_string(),"轧".to_string()),("鍘".to_string(),"铡".to_string()),("閘".to_string(),"闸".to_string()),("柵".to_string(),"栅".to_string()),("詐".to_string(),"诈".to_string()),("紮".to_string(),"扎".to_string()),("債".to_string(),"债".to_string()),("斎".to_string(),"斋".to_string()),("戦".to_string(),"战".to_string()),("桟".to_string(),"栈".to_string()),("綻".to_string(),"绽".to_string()),("嶄".to_string(),"崭".to_string()),("斬".to_string(),"斩".to_string()),("盞".to_string(),"盏".to_string()),("氈".to_string(),"毡".to_string()),("帳".to_string(),"帐".to_string()),("脹".to_string(),"胀".to_string()),("賬".to_string(),"账".to_string()),("漲".to_string(),"涨".to_string()),("張".to_string(),"张".to_string()),("趙".to_string(),"赵".to_string()),("轍".to_string(),"辙".to_string()),("這".to_string(),"这".to_string()),("鎮".to_string(),"镇".to_string()),("陣".to_string(),"阵".to_string()),("診".to_string(),"诊".to_string()),("偵".to_string(),"侦".to_string()),("貞".to_string(),"贞".to_string()),("針".to_string(),"针".to_string()),("掙".to_string(),"挣".to_string()),("証".to_string(),"证".to_string()),("鄭".to_string(),"郑".to_string()),("猙".to_string(),"狰".to_string()),("睜".to_string(),"睁".to_string()),("執".to_string(),"执".to_string()),("職".to_string(),"职".to_string()),("幟".to_string(),"帜".to_string()),("摯".to_string(),"挚".to_string()),("擲".to_string(),"掷".to_string()),("質".to_string(),"质".to_string()),("紙".to_string(),"纸".to_string()),("織".to_string(),"织".to_string()),("衆".to_string(),"众".to_string()),("種".to_string(),"种".to_string()),("腫".to_string(),"肿".to_string()),("終".to_string(),"终".to_string()),("鐘".to_string(),"钟".to_string()),("軸".to_string(),"轴".to_string()),("皺".to_string(),"皱".to_string()),("驟".to_string(),"骤".to_string()),("燭".to_string(),"烛".to_string()),("築".to_string(),"筑".to_string()),("貯".to_string(),"贮".to_string()),("鋳".to_string(),"铸".to_string()),("駐".to_string(),"驻".to_string()),("豬".to_string(),"猪".to_string()),("諸".to_string(),"诸".to_string()),("転".to_string(),"转".to_string()),("専".to_string(),"专".to_string()),("磚".to_string(),"砖".to_string()),("荘".to_string(),"庄".to_string()),("粧".to_string(),"妆".to_string()),("樁".to_string(),"桩".to_string()),("墜".to_string(),"坠".to_string()),("綴".to_string(),"缀".to_string()),("贅".to_string(),"赘".to_string()),("錐".to_string(),"锥".to_string()),("諄".to_string(),"谆".to_string()),("濁".to_string(),"浊".to_string()),("資".to_string(),"资".to_string()),("縦".to_string(),"纵".to_string()),("総".to_string(),"总".to_string()),("蹤".to_string(),"踪".to_string()),("綜".to_string(),"综".to_string()),("組".to_string(),"组".to_string()),("詛".to_string(),"诅".to_string()),("賺".to_string(),"赚".to_string()),("鑽".to_string(),"钻".to_string()),

        // Overwrite from simplified characters.
        ("舘".to_string(), "馆".to_string()),
        ("郁".to_string(), "鬰".to_string()),
        ("连".to_string(), "連".to_string()),
        ("决".to_string(), "诀".to_string()),
        ("来".to_string(), "來".to_string()),
        ("脚".to_string(), "腳".to_string()),
        ("。".to_string(), " ⸰ ".to_string()),
        ("、".to_string(), "︑".to_string()),
            ],

            overwrites: vec![
        ("贵样".to_string(), "贵様".to_string()),
        ("危险".to_string(), "危險".to_string()),
        ("优秀ゐ".to_string(), "优秀の".to_string()),
        ("ラーㄨン".to_string(), "うーメソ".to_string()),
        ("贰⊐゛贰⊐゛".to_string(), "二ゴ二ゴ".to_string()),
        ("ワクラ亻ナ".to_string(), "ワクう亻ナ".to_string()),
        ("レヌㇳラソ".to_string(), "レヌㇳうン".to_string()),
        ("(レなㄜい)".to_string(), "(しなさい)".to_string()),
            ],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build() {
        let _ = Dict::build();
    }

    #[test]
    fn convert() {
        let s = Dict::build()
            .convert("貴方は優等生故、ラーメンをしなさい。あカさタなハまヤらワん".to_string());
        assert_eq!(
            s,
            "贵様は优秀学生故︑うーメソ(しなさい) ⸰ あカㄜ夕な八まヤ꘥ワƕ"
        );
    }
}
